version: '3'
services:
  node-builder:
    image: phantasma-node-builder
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./DOCKER/DockerfileNodeBuilder
    volumes:
      - node_build:/app/build
    entrypoint: /bin/bash -c "tail -f /dev/null"
  node:
    image: phantasma-node:latest-amd64
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./DOCKER/DockerfileNodeWin
    environment:
      - NODE_ID=0
    volumes:
      - node_build:/app/build
    ports:
      - "7077:7077"
      - "26056-26058:26056-26058"
    depends_on: 
      - node-builder
    entrypoint: /bin/bash -c "mkdir -p /app/node/config/ && cp -rf /app/config/node0/* /app/node/config/ && cp -r /app/node/config/config.json /app/node/config.json && /app/wrapper.sh"
  node1:
      image: phantasma-node:latest-amd64
      platform: linux/amd64
      build:
        context: .
        dockerfile: ./DOCKER/DockerfileNodeWin
      environment:
        - NODE_ID=1
      volumes:
        - node_build:/app/build
      ports:
        - "7078:7078"
        - "26156-26158:26156-26158"
      depends_on:
        - node-builder
      entrypoint: /bin/bash -c "mkdir -p /app/node/config/ && cp -rf /app/config/node1/* /app/node/config/ && cp -r /app/node/config/config.json /app/node/config.json && /app/wrapper.sh"
  node2:
    image: phantasma-node:latest-amd64
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./DOCKER/DockerfileNodeWin
    environment:
      - NODE_ID=2
    volumes:
      - node_build:/app/build
    ports:
      - "7079:7079"
      - "26256-26258:26256-26258"
    depends_on:
      - node-builder
    entrypoint: /bin/bash -c "mkdir -p /app/node/config/ && cp -rf /app/config/node2/* /app/node/config/ && cp -r /app/node/config/config.json /app/node/config.json && /app/wrapper.sh"
    
  node3:
    image: phantasma-node:latest-amd64
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./DOCKER/DockerfileNodeWin
    environment:
      - NODE_ID=3
    volumes:
      - node_build:/app/build
    ports:
      - "7080:7080"
      - "26356-26358:26356-26358"
    depends_on:
      - node-builder
    entrypoint: /bin/bash -c "mkdir -p /app/node/config/ && cp -rf /app/config/node3/* /app/node/config/ && cp -r /app/node/config/config.json /app/node/config.json && /app/wrapper.sh"

networks:
  phantasma-nodes:
    driver: bridge
    
volumes:
  node_data:
  node_build: