name: .NET CI

on: [push, pull_request]

permissions:
  pull-requests: write
  actions: write
  issues: write
  
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
  
      - name: Install dependencies
        run: |
          sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev
          sudo apt-get install libc6-dev libicu-dev libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev libzstd-dev librocksdb-dev
          sudo apt-get install librocksdb-dev
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release  --no-restore

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Combine Coverage Output
        run: reportgenerator "-reports:coverage/**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:Cobertura -assemblyfilters:"-Phantasma.Tendermint;-Phantasma.Tendermint.RPC;-Phantasma.Business.Tests;-Phantasma.Core.Tests;-phantasma-node;-Phantasma.Tests;-Phantasma.Infrastructure"

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/Cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Code Coverage Report
        run: |
          echo "test=tests" >> $GITHUB_OUTPUT

      - name: Code Coverage Report
        run: |
          echo "coverage=$(cat coverage/code-coverage-results.md)" >> $GITHUB_OUTPUT
  
  MyTest:
    name: Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Store Variable
        id: my-test
        run: |
          mkdir -p /test/
          echo hello > /test/world.txt
          echo "localTest=thisismine" >> $GITHUB_OUTPUT
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: /test/world.txt
          
  MyTest2:
    needs: [MyTest]
    name: Test2
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: /test/
          
      - name: Get Variable
        run: cat /test/world.txt
    
  Comment:
    name: Comment on PR
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        
      - name: Get Code Coverage
        run: |
          echo ${{needs.build.outputs.coverage}} > code-coverage-results.md
          
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          message: |
              This is just a test
              {{needs.build.outputs.tests}}
              ${{ needs.build.outputs.coverage }}
          #filePath: code-coverage-results.md
        
     # - name: Add Coverage PR Comment
     #   uses: marocchino/sticky-pull-request-comment@v2
        #env:
          #name: Pull Request Deployment
          #GITHUB_TOKEN: ${{ secrets.PR_KEY }}
     #   if: github.event_name == 'pull_request'
     #   with:
     #     recreate: true
     #     path: code-coverage-results.md
     #     GITHUB_TOKEN: ${{secrets.PR_KEY}}